### PR TITLE
Add a bash script to install the python3 required modules

### PR DESCRIPTION
**Pull request by EsteveAguilera**
I've faced the need to install the required modules and thought that with a script it will be much easy for newcomers.

PS: Maybe you can find a better folder name like "installation" 🤷‍♂

### CODE REVIEW

**Comment by ctrl-alt-d** [comment]
Because this project has a `requirements.txt` file I suggest to use it:

```
python3 -m pip install -r requirements.txt
```

or just:

```
pip3 install -r requirements.txt
```

**Comment by EsteveAguilera** [comment]
Sounds much more easy to maintain... It's a LGTM!

@moiatgit if you prefer the @ctrl-alt-d option, I can close the PR and let @ctrl-alt-d do a new one with his approach!

**Comment by ctrl-alt-d** [comment]
Maybe the script is not needed, just add an "install from Github" section on `readme.rst` with download, [create virualenv] and install requirements instructions.

**Comment by moiatgit** [comment]
Thanks a lot for your interest in this project!
As @ctrl-alt-d said, `pip install -Ur requirements.txt` should do the trick
You made a good point here: documentation should explain this point!

**Pull request closed without merging**
